### ISSUE TITLE
NPM repo does not exist

### ISSUE THREAD

**Issue by meiremans** [janb87/hyperledger-fabric-chaincode-dev-setup#34]
> npm install @kunstmaan/hyperledger-fabric-chaincode-dev --save

is mentioned, but this repo doesn't exist in NPM

**Comment by janb87** [comment]
There was I typo in the docs, should have been:
`npm install @kunstmaan/hyperledger-fabric-chaincode-dev-setup --save`

Should also be fixed on npm when we publish a new version of the package.
